[project]
site_name = "Speedtest Tracker"
site_description = "Self-hosted application that monitors the performance and uptime of your internet connection."
site_author = "Alex Justesen"
site_url = "https://www.speedtest-tracker.dev"
repo_url = "https://github.com/alexjustesen/speedtest-tracker"
repo_name = "alexjustesen/speedtest-tracker"
copyright = "Copyright &copy; 2026 alexjustesen"
extra_css = ["stylesheets/extra.css"]

nav = [
  {"Home" = "index.md"},
  {"Getting Started" = [
    "getting-started/index.md",
    {"Installation" = [
      "getting-started/installation/docker-compose.md",
      "getting-started/installation/docker.md",
    ]},
    {"Configuration" = [
      "getting-started/configuration/environment-variables.md",
      "getting-started/configuration/database-drivers.md",
      "getting-started/configuration/reverse-proxies.md",

    ]},
    {"Settings" = [
      "getting-started/settings/thresholds.md",
      {"Notifications" = [
        "getting-started/settings/notifications/index.md",
        "getting-started/settings/notifications/database.md",
        "getting-started/settings/notifications/mail.md",
        "getting-started/settings/notifications/webhook.md",
        "getting-started/settings/notifications/apprise.md"
      ]},
      {"Data Integration" = [
        "getting-started/settings/data-integration/index.md",
        "getting-started/settings/data-integration/influxdb2.md",
        "getting-started/settings/data-integration/prometheus.md"
      ]}
    ]},
    {"Security" = [
      "getting-started/security/authentication.md",
      "getting-started/security/authorization.md",
      "getting-started/security/encryption.md"
    ]}
  ]},
  {"Help & Troubleshooting" = [
    "help/general.md",
    "help/speedtest-errors.md",
    "help/application-errors.md",
    "help/notification-errors.md",
    "help/data-export-errors.md"
  ]},
  {"Changelog" = "https://github.com/alexjustesen/speedtest-tracker/releases"},
  {"API" = [
    "api/authorization.md"
  ]},
  {"Other" = [
    "other/commands.md",
    "other/speedtest-process.md",
    "other/data-dictionary.md",
    "other/community-projects.md"
  ]},
  {"Contributing" = [
    "contributing/getting-started.md",
    {"Documentation" = [
      "contributing/documentation.md"
    ]},
    {"Code" = [
      "contributing/development-environment.md"
    ]}
  ]}
]

[project.theme]
logo = "img/speedtest-tracker-icon.png"
favicon = "img/favicon.ico"
language = "en"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow"
]


[[project.theme.palette]]
scheme = "default"
accent = "orange"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
