name: "Link Checker"

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  lychee-link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run Lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # arguments passed to lychee
          args: --root-dir "$(pwd)" --verbose --no-progress './**/*.md'
          fail: true